### ISSUE TITLE
Flow chart - Vertically-stacked conditionals throw right-branch objects further and further away

### ISSUE THREAD

**Issue by pevinkark** [hugoabernier/react-diagram-webparts#11]
Loving these web parts BTW - great work :)

When creating a flow chart with multiple conditional objects in a vertical arrangement, the right branch seems to get rendered longer and longer, pushing the objects further away, making the chart wider and making the text smaller.
Is this intentional and/or is there a syntactic way to make the flow chart more columnar and legible?

Here's some sample flowchart code to illustrate:

st=>start: Start
cond1=>condition: Are we going
to op1?
cond2=>condition: Are we going
to op2?
cond3=>condition: Are we going
to op3?
op1=>operation: op1
op2=>operation: op2
op3=>operation: op3
e=>end
st(bottom)->cond1
cond1(yes,right)->op1
cond1(no,bottom)->cond2
cond2(yes,right)->op2
cond2(no,bottom)->cond3
cond3(yes,right)->op3
cond3(no,bottom)->e

Thanks,
Kevin

**Comment by hugoabernier** [comment]
Thanks Kevin,

I agree that it can get quite annoying when it tries to render wide charts.

You can indicate whether you want nodes to align or not by using the `cond(align-next=no)` indicator to help keep the size in check. For example, here is the same diagram with a few `align-next=no` for every other condition:

```Markdown
st=>start: Start
cond1=>condition: Are we going
to op1?
cond2=>condition: Are we going
to op2?
cond3=>condition: Are we going
to op3?
op1=>operation: op1
op2=>operation: op2
op3=>operation: op3
op4=>operation: must be
going to
op4
e=>end
st(bottom)->cond1
cond1(align-next=no,yes,right)->op1
cond1(no,bottom)->cond2
cond2(yes,right)->op2
cond2(no,bottom)->cond3
cond3(align-next=no,yes,right)->op3
cond3(no,bottom)->e
```

Which renders the chart as follows:
![image](https://user-images.githubusercontent.com/13972467/56502879-e0982f80-64e1-11e9-975d-354da2cab486.png)

I have been debating whether I should add the ability to control dimensions on the web parts. If you have any suggestions for a different way to handle this, I'd be happy to look into it.

I hope this helps?

**Comment by pevinkark** [comment]
Hi Hugo,

Many thanks for the prompt reply and your below suggestion.
I tried the below flowchart code but couldn’t get it working.
I then realised my project was out of date and redeployed it but I still get the following:
[cid:image001.png@01D4F92D.EB494880]
![image](https://user-images.githubusercontent.com/49870464/56510328-5ec7f680-6521-11e9-8ab5-1b30fd074853.png)

(Invalid Direction. Expecting 'top', 'bottom', 'left', or 'right')

I can paste it OK into  the flowchart.js.org site fine, but it doesn’t seem to work inside the web part.

Am I missing something?

Thanks,
Kevin

**Comment by hugoabernier** [comment]
I'll take a look at it tonight, my syntax verification may be a bit out of sync with the version that's posted.  Sorry for the inconvenience!

**Comment by hugoabernier** [comment]
@pevinkark Version 1.3 of the web part should solve the issues with parsing `align-next` instructions. Apologies for the inconvenience.

Thanks again for taking the time to report the issue!

**Comment by pevinkark** [comment]
@hugoabernier Thank you. I was able to implement the align-next feature, but on the object declaration rather than the relationship declaration. Final working flowchart code with vertically-aligned operations as below:

st=>start: Start
cond1(**align-next=no**)=>condition: Are we going
to op1?
cond2(**align-next=no**)=>condition: Are we going
to op2?
cond3(**align-next=no**)=>condition: Are we going
to op3?
op1=>operation: op1
op2=>operation: op2
op3=>operation: op3
e=>end
st(bottom)->cond1
cond1(yes,right)->op1
cond1(no,bottom)->cond2
cond2(yes,right)->op2
cond2(no,bottom)->cond3
cond3(yes,right)->op3
cond3(no,bottom)->e
