### ISSUE TITLE
How can i add hyperlink or anchor tag to one of the box

### ISSUE THREAD

**Issue by harshdamaniahd** [hugoabernier/react-diagram-webparts#8]
Firstly I really want to appreciate the effort. This is really helpful webpart.
I am unable to add a link to a box

**Comment by hugoabernier** [comment]
Thank you, it means a lot!

Unfortunately, none of them allow a hyperlink embedded wihin the text, yet. You can, however, associate a hyperlink to a node in FlowChart and Mermaid diagrams:

## Flowchart
The flowchart diagram allows you to associate a node with a URL by adding `:>` after the label.

Use the following syntax:

```
nodetype: NodeLabel:>Url[Target]
```

For example:

```
start: Start:>https://github.com
```
or 
```
start: Start:>https://github.com[blank]
```

## Mermaid

Add a `click` command at the end of your diagram indicating which node you wish to convert to a hyperlink. The hyperlink's text will be the text of the node.

Use the following syntax:
```
click NodeName "URL" "Tooltip"
```

For example:

```
click A "http://github.com"
```
Or:
```
click A "http://github.com" "Go to GitHub"
```

Will produce the following link:
![image](https://user-images.githubusercontent.com/13972467/56143706-ff8d4380-5f6e-11e9-8c5f-636beace8b81.png)


You can associate a link to more than one node if you wish:
```
click A,B "http://github.com" "tooltip text"
```

## Sequence
Do not support anchors yet. I'd have to make a PR to https://github.com/bramp/js-sequence-diagrams, but it sure would be a great idea.

I hope this helps?

**Comment by harshdamaniahd** [comment]
Thanks....it helps :-)

**Comment by harshdamaniahd** [comment]
It works for flowchart.
I tried this for mermaid, but it doesn't work, also after adding link, the node text disappears
![image](https://user-images.githubusercontent.com/11780473/56192710-45a9dc00-602f-11e9-8147-f662c28c0819.png)

graph LR
  A[Square Rect] -- Link text --> B((Circle))
  A --> C(Round Rect)
  B --> D{Rhombus}
  C --> D
  
  click A "http://github.com" "Go to GitHub"

**Comment by hugoabernier** [comment]
Thanks for reporting this, I'll take a look at it tonight and let you know.

**Comment by hugoabernier** [comment]
@harshdamaniahd I've added the ability to enable HTML Labels for mermaid diagrams. Turns out that links are only rendered in HTML labels. 

I hope this helps?
